name: Validate PR

on:
  pull_request:
    branches: [master]
    paths:
      - "Containerfile.template"
      - "base-image.lock"
      - "scripts/**"
      - "configs/**"
      - "Makefile"
      - ".github/workflows/build-image.yaml"
      - ".github/workflows/validate_pr.yaml"

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-image.yaml
    with:
      push: false
      image_name: bootc-arch-base
